[package]
name = "chat-rs"
version = "0.1.0"
authors = ["Johnny Santos <johnnyadsantos@gmail.com>"]
edition = "2018"

[dependencies]
clap = "~2.33.3"
ctrlc = { version = "~3.2.0", features = ["termination"] }
